### ISSUE TITLE
because the `selectFromStore` only can be use in functional component, how to get the store items out of component? 

### ISSUE THREAD

**Issue by moonshineBoy** [StevenJPx2/staatshelfer#3]
Hi,
because the `selectFromStore` only can be use in functional component,
how to get the store items out of component? 

such as I want to create a `initialize.ts` to initial the states of the store items:

```
App.tsx
initialize.ts
```

initialize.ts
```
export const initAllState = async () => {
  const { setUserId } = selectFromStore(
    useMainStore,
    ["userId"]
  )

  const userId = await initUserId()
  setUserId(userId)
}
```

but when I execute it, I will get error:

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
    at Object.throwInvalidHookError (react-dom_client.js?v=069e902f:11501:17)
    at useRef (chunk-B7VAMJ3U.js?v=069e902f:1074:29)
    at useSyncExternalStoreWithSelector2 (zustand.js?v=069e902f:162:25)
    at useStore (zustand.js?v=069e902f:291:17)
    at useBoundStore (zustand.js?v=069e902f:308:51)
    at selectFromStore (staatshelfer.js?v=069e902f:5:42)
    at initAllState (initialize.ts:37:25)
    at App.tsx:19:5
    at commitHookEffectListMount (react-dom_client.js?v=069e902f:16915:34)
    at commitPassiveMountOnFiber (react-dom_client.js?v=069e902f:18156:19)
```

**Comment by StevenJPx2** [comment]
Were you able to solve the issue?

**Comment by moonshineBoy** [comment]
@StevenJPx2 Thanks your reply,
selectFromStore only can be used in React Component.
I solved it by importing `selectFromStore` in App.tsx,
App.tsx:
```
import { selectFromStore } from "staatshelfer";
```

and pass it to the `store/initialState.ts`'s function.
